services:
  postgres:
    image: postgres:18
    ports:
      - "5439:5432"
    environment:
      POSTGRES_PASSWORD: mysecret

  vault:
    image: hashicorp/vault:2.0
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -dev -dev-listen-address="0.0.0.0:8200" -dev-root-token-id="root"

  pgweb:
    image: sosedoff/pgweb:latest
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      PGWEB_DATABASE_URL: "postgres://postgres:mysecret@postgres:5432/postgres?sslmode=disable"

  server:
    build:
      dockerfile: server/Dockerfile
    env_file: server/.env
    volumes:
      - ./server:/app/server:cached
