name: Prepare next release 🚀

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Run release draft to extract labels ☕️
    runs-on: ubuntu-latest
    steps:
    - name: Run release draft to extract labels ☕️
      uses: tchoupinax/repo-config/shared-actions/steps/dx/prepare-draft-release@a9365b7dea332dfa67e1f5c1b861f6ae147111f3 # v0
      with:
        appId: ${{ secrets.DEPLOY_APP_ID }}
        privateKey: ${{ secrets.DEPLOY_APP_KEY }}
