name: Pull request analysis

on:
  pull_request:
    branches:
    - "*"

jobs:
  labels:
    name: Autodetect labels 🔍
    runs-on: ubuntu-latest
    steps:
    - name: Autodetect labels 🔍
      uses: tchoupinax/repo-config/shared-actions/steps/dx/automatically-apply-labels@v0
      with:
        appId: ${{ secrets.DEPLOY_APP_ID }}
        privateKey: ${{ secrets.DEPLOY_APP_KEY }}

  build-ui:
    name: "🟢 Build user interface (Nuxt.js project)"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: "Setup PNPM"
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        version: 10.30.3

    - name: Use Node.js 25
      uses: actions/setup-node@v6
      with:
        node-version: 25
        cache: "pnpm"

    - name: Build, lint and test the package
      run: |
        pnpm install --frozen-lockfile --filter timelord-ui
        pnpm build --filter timelord-ui

  build-server:
    name: "🟣 Build server and generate prisma"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: "Setup PNPM"
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        version: 10.30.3

    - name: Use Node.js 24
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: "pnpm"

    - name: Build, lint and test the package
      run: |
        pnpm install --frozen-lockfile --filter timelord-server
        cd server && pnpm build:ci
      env:
        API_URL: "_"
        CI_COMMIT_SHA: "_"
        CI_PIPELINE_CREATED: "1"
        DATABASE_URL: "_"
        JOB_DEFAULT_TIMEOUT: "_"
        OIDC_CLIENT_ID: "_"
        OIDC_CLIENT_SECRET: "_"
        OIDC_CONFIGURATION_URL: "_"
        OIDC_PROVIDER_IMAGE: "_"
        OIDC_PROVIDER_NAME: "_"
        UI_URL: "_"
        VAULT_ADDR: "_"
        VAULT_PATH: "_"
        VAULT_TOKEN: "_"

  build-agent:
    name: "🔵 Build agent binary"
    runs-on: ubuntu-latest
    steps:
    - name: Check build success 🦫
      uses: tchoupinax/repo-config/shared-actions/steps/golang/goreleaser-build-only@v0
      with:
        workingDirectory: agent
