name: Releasing

on:
  push:
    tags:
    - v*

permissions:
  contents: write
  packages: write

jobs:
  build-ui:
    name: "🟢 Release user interface 🐳"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

    - name: Setup PNPM
      uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

    - name: Use Node.js 25
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: 25
        cache: "pnpm"

    - name: Build, lint and test the package
      run: |
        pnpm install --frozen-lockfile --filter @timelord/ui
        pnpm build --filter @timelord/ui

    - name: Set up QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6
      with:
        images: |
          ghcr.io/tchoupinax/timelord-ui
          tchoupinax/timelord-ui
        flavor: latest=true
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{raw}}
    - name: Build and push
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
      with:
        context: "./ui"
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}

  build-server:
    name: "🟣 Release server 🐳"
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
    - name: Checkout
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

    - name: Setup PNPM
      uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

    - name: Use Node.js 24
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: 24
        cache: "pnpm"

    - name: Build, lint and test the package
      run: |
        pnpm install --frozen-lockfile --filter @timelord/server
        cd server && pnpm build:ci
      env:
        API_URL: "_"
        CI_COMMIT_SHA: "_"
        CI_PIPELINE_CREATED: "1"
        DATABASE_URL: "_"
        JOB_DEFAULT_TIMEOUT: "_"
        OIDC_CLIENT_ID: "_"
        OIDC_CLIENT_SECRET: "_"
        OIDC_CONFIGURATION_URL: "_"
        OIDC_PROVIDER_IMAGE: "_"
        OIDC_PROVIDER_NAME: "_"
        UI_URL: "_"
        VAULT_ADDR: "_"
        VAULT_PATH: "_"
        VAULT_TOKEN: "_"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6
      with:
        images: |
          ghcr.io/tchoupinax/timelord-server
          tchoupinax/timelord-server
        flavor: latest=true
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{raw}}

    - name: Build and push
      uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
      with:
        context: "."
        file: "./server/Dockerfile"
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha,scope=timelord-server
        cache-to: type=gha,mode=max,scope=timelord-server
        build-args: |
          CI_COMMIT_SHA=${{ github.ref_name }}
          CI_PIPELINE_CREATED=111111111

  build-agent:
    name: "🔵 Release agent 🐳"
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4
      with:
        driver: docker-container

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Check build success 🦫
      uses: tchoupinax/repo-config/shared-actions/steps/golang/goreleaser-release@a9365b7dea332dfa67e1f5c1b861f6ae147111f3 # v0
      with:
        workingDirectory: agent
        appId: ${{ secrets.DEPLOY_APP_ID }}
        privateKey: ${{ secrets.DEPLOY_APP_KEY }}
